### ISSUE TITLE
I'm on Chp. 9, Learning Node.js

### ISSUE THREAD

**Issue by SecretTitle** [marcwan/LearningNodeJS#32]
Where do you recommend I install "mysql" to?;  I'm running Windows.  Can I install it anywhere?;  Do I need to set an environment variable when I'm finished?

Thank you in advance!

**Comment by marcwan** [comment]
Hey, thanks for the comments!

Honestly, it doesn't matter — I believe it chooses something reasonable by default like C:\Program Files\MySQL or some such thing. That's going to be just fine.

Otherwise, if you prefer your stuff more "self-contained", you could create a new c:\learningnode folder and just put everything in there.  Not a big deal either way!

Good luck!
